# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: match.proto for package ''

require 'grpc'
require_relative 'match_pb'

module ScoreNotifications
  class Service

    include GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'ScoreNotifications'

    rpc :SubscribeToTournament, SubscribeRequest, stream(ScoreReply)
  end

  Stub = Service.rpc_stub_class
end
