# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: match.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("match.proto", :syntax => :proto3) do
    add_message "Team" do
      optional :name, :string, 1
      optional :score, :int32, 2
      optional :is_ct, :bool, 3
      repeated :alive_members, :string, 4
    end
    add_message "SubscribeRequest" do
      optional :tournament, :string, 1
      optional :frequency, :int32, 2
    end
    add_message "ScoreReply" do
      optional :first_team, :message, 1, "Team"
      optional :second_team, :message, 2, "Team"
      optional :score, :string, 3
      optional :win_condition, :enum, 4, "WinConditions"
      optional :datetime, :string, 5
    end
    add_enum "WinConditions" do
      value :KILLED_ALL, 0
      value :TIMEOUT, 1
      value :BOMB_DEFUSED, 2
      value :BOMB_EXPLODED, 3
    end
  end
end

Team = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Team").msgclass
SubscribeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SubscribeRequest").msgclass
ScoreReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ScoreReply").msgclass
WinConditions = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("WinConditions").enummodule
